type = "card"
title = "Blog"

[[items]]
title = "Farewell to Paper People: From Human Simulation to Human Simulator"
link = "https://medium.com/@zhouyufan365/farewell-to-paper-people-from-human-simulation-to-human-simulator-02c06ac27fb5"
