[site]
title = "Yufan Zhou"
description = "PhD Student at KU Leuven"
favicon = "/favicon.svg"
last_updated = "April 6, 2026"

[author]
name = "Yufan Zhou"
title = "PhD Student"
institution = "KU Leuven"
avatar = "/bio.jpg"

[social]
email = "yufan.zhou@kuleuven.be"
location = "Leuven, Belgium"
location_url = "https://maps.google.com/?q=Celestijnenlaan+200A+Leuven"
location_details = [
  "Celestijnenlaan 200A,",
  "Leuven, Belgium"
]
google_scholar = "https://scholar.google.com/citations?user=aqHZezMAAAAJ&hl=zh-CN"
github = "https://github.com/thzva"
linkedin = "https://www.linkedin.com/in/yufan-zhou-9007a7291/"

[features]
enable_likes = true
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
mode = "fixed"
fixed_locale = "en"
persist = false
switcher = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"

[[navigation]]
title = "Miscellaneous"
type = "page"
target = "miscellaneous"
href = "/miscellaneous"
