[[news]]
date = "2026-04"
content = "One first-author paper is accepted by UMAP 2026 🎉"

[[news]]
date = "2025-11"
content = "Our paper is awarded as a Spotlight at NeurIPS 2025 LAW Workshop 🏅"

[[news]]
date = "2025-03"
content = "One co-author paper is accepted by IET Computer Vision 🎉"

[[news]]
date = "2024-05"
content = "One co-author paper is accepted by FedCSIS 2024 🎉"
